# Generated by Django 5.2 on 2025-04-14 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garbage_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('E-Waste', 'E-Waste'), ('Other', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pick_up_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.users')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-id'],
            },
        ),
    ]
