# Generated by Django 5.2 on 2025-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarbageRegistration',
            new_name='Garbage',
        ),
    ]
