# Generated by Django 5.2 on 2025-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_rename_garbageregistration_garbage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garbage',
            options={'ordering': ['-id'], 'verbose_name': 'Garbage', 'verbose_name_plural': 'Garbages'},
        ),
    ]
