# Generated by Django 5.2 on 2025-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_alter_garbage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
