# Generated by Django 5.2 on 2025-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagetruck',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
