# Generated by Django 5.2 on 2025-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_garbagetruck_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagetruck',
            name='truck_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
