# Generated by Django 5.2 on 2025-04-06 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('THIRUVANANTHAPURAM', 'THIRUVANANTHAPURAM'), ('KOLLAM', 'KOLLAM'), ('PATHANAMTHITTA', 'PATHANAMTHITTA'), ('ALAPPUZHA', 'ALAPPUZHA'), ('KOTTAYAM', 'KOTTAYAM'), ('IDUKKI', 'IDUKKI'), ('ERNAKULAM', 'ERNAKULAM'), ('THRISSUR', 'THRISSUR'), ('PALAKKAD', 'PALAKKADU'), ('MALPPURAM', 'MALAPPURAM'), ('KOZHIKODE', 'KOZHIKODE'), ('WAYANAD', 'WAYANADU'), ('KANNUR', 'KANNUR'), ('KASARGOD', 'KASARGOD')], max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
    ]
